# Generated by Django 3.2.2 on 2021-05-11 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fspId', models.CharField(max_length=8)),
                ('name', models.TextField(max_length=32)),
                ('path', models.TextField(max_length=32)),
                ('status', models.TextField(max_length=16)),
                ('number_of_last_download', models.IntegerField()),
                ('number_of_users', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
